server:
  port: 8762

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8
    username: root
    password:
  application:
    name: service-hi
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
  session:
    store-type: redis


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
tx-lcn:
  client:
    manager-address: 192.168.5.213:8070
    resource-order: 0
  logger:
    enabled: false
  message:
    netty:
      wait-time: 5000
  springcloud:
    loadbalance:
      enabled: false


